# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "Pipekit CLI"
  homepage "https://pipekit.io/"
  version "4.26.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pipekit/cli/releases/download/v4.26.2/cli_4.26.2_darwin_amd64.tar.gz"
      sha256 "541c27d13f3a6294553e8e9d7071a59426454073c5bae728d41ad949860cf3f9"

      def install
        bin.install "pipekit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pipekit/cli/releases/download/v4.26.2/cli_4.26.2_darwin_arm64.tar.gz"
      sha256 "6ab9a23656b39bb2c32643d41fa814d7e8b3c6abfe46f2330a3e36134c9673b9"

      def install
        bin.install "pipekit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pipekit/cli/releases/download/v4.26.2/cli_4.26.2_linux_amd64.tar.gz"
        sha256 "75921a7c9611f25d58c831e01a20df438d4ed9d66613dbf88b21dfb0c0e48905"

        def install
          bin.install "pipekit"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pipekit/cli/releases/download/v4.26.2/cli_4.26.2_linux_arm64.tar.gz"
        sha256 "a1fffba00766131af202cd0d5f9825cf7c8d7b868ad5566695b6f008c9f5ad02"

        def install
          bin.install "pipekit"
        end
      end
    end
  end
end
