# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "Pipekit CLI"
  homepage "https://pipekit.io/"
  version "6.65.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pipekit/cli/releases/download/v6.65.3/cli_6.65.3_darwin_amd64.tar.gz"
      sha256 "e80ff6747b3c31b0876fbd6121ff03d52b203fbd89b05645c04abc8d38c83dbe"

      define_method(:install) do
        bin.install "pipekit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pipekit/cli/releases/download/v6.65.3/cli_6.65.3_darwin_arm64.tar.gz"
      sha256 "75345942b82212b8f469a88b99a9d1da9762804c31c5d121daf1e3efb7a24888"

      define_method(:install) do
        bin.install "pipekit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pipekit/cli/releases/download/v6.65.3/cli_6.65.3_linux_amd64.tar.gz"
      sha256 "2ae1ee3299853d7137cb7f8204199f2bfe49814642497cff4ca39c172e2e6e37"
      define_method(:install) do
        bin.install "pipekit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pipekit/cli/releases/download/v6.65.3/cli_6.65.3_linux_arm64.tar.gz"
      sha256 "facaddae575a625bcc3c0940c7aa80b422ffc2bcf64a980e02b3d63441a9554b"
      define_method(:install) do
        bin.install "pipekit"
      end
    end
  end
end
