# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "Pipekit CLI"
  homepage "https://pipekit.io/"
  version "4.20.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pipekit/cli/releases/download/v4.20.3/cli_4.20.3_darwin_amd64.tar.gz"
      sha256 "72dded2d0800a451a53634de09e96d92430818dddba05d7ef1a6c002ab97f549"

      def install
        bin.install "pipekit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pipekit/cli/releases/download/v4.20.3/cli_4.20.3_darwin_arm64.tar.gz"
      sha256 "809f20b60c45a5a33cc2fb5cb5ea2b0a611a5f9968b7e2706dcc3eee7557c300"

      def install
        bin.install "pipekit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pipekit/cli/releases/download/v4.20.3/cli_4.20.3_linux_amd64.tar.gz"
        sha256 "c4bf373099bbf5a119322f4d61bfdf81a3d460532a8b1e1a5d0ac88d2a21b67e"

        def install
          bin.install "pipekit"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pipekit/cli/releases/download/v4.20.3/cli_4.20.3_linux_arm64.tar.gz"
        sha256 "a18f7e52249dc8568605158ad8e46ae6c47587202983be2bf09fa20e33f246a7"

        def install
          bin.install "pipekit"
        end
      end
    end
  end
end
